name = "KataGraph"
uuid = "1cfaaf34-ec90-487b-b594-ba2a92d441cd"
authors = ["Chad Hovey <hovey@me.com> and contributors"]
version = "0.1.0"

[deps]
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
