name = "QuadraticFormula"
uuid = "39f9687e-e4a8-4d89-ad06-097a6207ea2f"
authors = ["Anirudh Patel <patel.anirudh0025@gmail.com> and contributors"]
version = "0.1.0"

[deps]
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
TypeClasses = "addcc920-e0cf-11e8-30b7-0fb08706b574"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
