name = "bbox"
uuid = "dd0d5e91-03b6-41b4-a3b1-4217fc9942a5"
authors = ["Chad Hovey <hovey@me.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
