using bbox
using FileIO
using GeometryBasics
using MeshIO
using Test

const tf = joinpath(dirname(@__FILE__), "testfiles")

function test_face_indices(mesh)
    for face in faces(mesh)
        for index in face
            pass = firstindex(coordinates(mesh)) <= index <= lastindex(coordinates(mesh))
            pass || return false
        end
    end
    return true
end

@testset "bbox.jl" begin
    # Write your tests here.
    @test 4 ± 2 == [2, 6]

    # examples from https://docs.julialang.org/en/v1/stdlib/Test/
    @test π ≈ 3.14 atol = 0.01
    @testset "trigonometric identities" begin
        θ = 2 / 3 * π
        @test sin(-θ) ≈ -sin(θ)
        @test cos(-θ) ≈ cos(θ)
        @test sin(2θ) ≈ 2 * sin(θ) * cos(θ)
        @test cos(2θ) ≈ cos(θ)^2 - sin(θ)^2
    end

    # minimum working example final data type we might feed to
    # the function, excerpt from 
    # GitHub SIBL repo at the `sibl/geo/data/stl/sphere.stl` location.
    #
    # solid STL generated by MeshLab
    #     facet normal  1.259634e-01  9.611654e-01  2.455488e-01
    #       outer loop
    #         vertex   6.776129e-02  4.821303e-01  1.108122e-01
    #         vertex   4.890279e-02  4.862624e-01  1.043121e-01
    #         vertex   5.286912e-02  4.810396e-01  1.227211e-01
    #       endloop
    #     endfacet
    #     facet normal  1.215015e-01  8.930119e-01  4.333210e-01
    #       outer loop
    #         vertex   6.162572e-02  4.444005e-01  2.188959e-01
    #         vertex   7.487786e-02  4.465131e-01  2.108264e-01
    #         vertex   5.578082e-02  4.527939e-01  2.032373e-01
    #       endloop
    #     endfacet
    #     facet normal  2.674524e-01  9.364683e-01  2.269280e-01
    #       outer loop
    #         vertex   1.418558e-01  4.659817e-01  1.093728e-01
    #         vertex   1.247853e-01  4.738385e-01  9.706881e-02
    #         vertex   1.240194e-01  4.692471e-01  1.169191e-01
    #       endloop
    #     endfacet
    # endsolid vcg

    # MeshIO
    #https://github.com/JuliaIO/MeshIO.jl/blob/master/src/io/stl.jl
    # function load stl

    # from package mode
    # pkg> add FileIO MeshIO    
    # using FileIO
    # mesh = load("path/to/mesh.obj")
    # mesh = load("testfiles/cube.stl")

    # https://github.com/hovey/MeshIO.jl/blob/master/test/runtests.jl#L57
    msh = load(joinpath(tf, "cube.stl"))
    @test length(coordinates(msh)) == 36
    @test length(faces(msh)) == 12
    @test test_face_indices(msh)

end
